### PR TITLE
update new files

### PR DESCRIPTION
**Pull request by LinguList**
Please check how I proceed. Note that the dot between cluster elements preserves the integrity of phones. We use this in EDICTOR now to mark "evolving sound units". So I recommend to use a dot. Note how I do the segmentation first (it is done within "lex" already) and then modify the CV_Segments by passing Segments to it. Quite a good solution, I'd say for now. Worked well for me.

### CODE REVIEW

**Comment by LinguList** [comment]
You should re-run, as I ran without Glottolog with the `--dev` keyword.

**Comment by martino-vic** [comment]
Awesome, thank you! Had to manually resolve some conflicts because I have changed some things about the repo in the meanwhile (like fixing issue #4 with the wrongly transcribed geminates). Might have broken something during that process, but will rerun on my computer now, should work

**Comment by martino-vic** [comment]
Ran it from my laptop and it worked immediately :)

**Comment by martino-vic** [comment]
> You should re-run, as I ran without Glottolog with the `--dev` keyword.
[Well remembered](https://github.com/martino-vic/streitberggothic/issues/2#issuecomment-1008368024) 😁 but I got myself a new laptop with an SSD in the meanwhile so running without the --dev flag too now 😎

**Comment by martino-vic** [comment]
Okay I see the dot notation will save me some wrangling again when I want to check if it's a C-cluster or a V-cluster, so that's nice. I think the solution is quite elegant. When I had[ tried it myself](https://github.com/pavelsof/ipatok/blob/master/ipatok/tokens.py#L189) I was surprised how tricky it is to come up with a good code for this, even though the task seems so trivial.

**Comment by LinguList** [comment]
Yes, it seems trivial, right? And my code is not optimized, but we don't need optimized code, as we only run this once. Once I have understood WHY you need this, I'd add the code for clusters to LingPy or LingRex, so it can be used from there and is also tested.

**Comment by LinguList** [comment]
Gosh, you have so many tiny and potentially nice things in your loanpy, that it is a pity you never wrote it up. Did you read about our very simple alignment method we call "template alignment"? If phonotactics are fixed, this is also doing an excellent job, and no need to go with complex multi alignments.

**Comment by LinguList** [comment]
It is here: https://doi.org/10.5334/johd.12

**Comment by LinguList** [comment]
I mean, this alignment method is also something to be shared in an article. So you should make sure to write it up for your dissertation as a sub-chapter, so we can later quote and test it!

**Comment by martino-vic** [comment]
> Gosh, you have so many tiny and potentially nice things in your loanpy

Thanks!



> that it is a pity you never wrote it up

the problem is that my supervisors don't know and don't care about what I'm doing so I was missing this kind of reflection from outside and was just doing stuff without being able to estimate it's value or how to exactly convert it into something. Well at least I have to stepped out of that now.

> Did you read about our very simple alignment method we call "template alignment"?

I might have come across it shortly, not sure. The paper looks exciting, just skimmed it now quickly, will read more carefully later today



> If phonotactics are fixed,

Yeah so I figured out when applying the extracted sound correspondences for predictions, the most difficult part was to tell where to reconstruct sounds in the proto-language where there is nothing in its descendant. And so the multi-alignment (as this is apparently called) seemed to be a convenient work around: If 1 descendant sound corresponds to 2 proto-sounds, we've captured the disappeared one. For the loanword adaptation I fixed this differently, there the phonotactics is first fixed in a separate step, and then just the extracted sound correspondences applied (so there's no multi-alignment needed there)

**Comment by LinguList** [comment]
Did you check our most recent paper on trimming alignemnts, where we have a very simple procedure to predict non-existent elements, when having training data?

**Comment by LinguList** [comment]
> List, J.-M., N. Hill, and R. Forkel (2022): A new framework for fast automated phonological reconstruction using trimmed alignments and sound correspondence patterns. In: Proceedings of the 3rd Workshop on Computational Approaches to Historical Language Change. Association for Computational Linguistics 89-96.

https://aclanthology.org/2022.lchange-1.9.pdf

This technique (which we did not invent, we quote another source for it, but applied it first on multi-alignments) was a game-changer for me in predicting words, so if you do not use this, I recommend to think of using it, if you work in a supervised framework (but that is not yet clear to me, I am waiting for your first blog post to understand more ;)

**Pull request merged**
